matrix:
  platform:
  - linux/amd64
  - linux/arm64

labels:
  type: exec
  platform: ${platform}

steps:
- name: test-linux
  image: bash
  commands:
  - export VERSION=$([ -z $CI_COMMIT_TAG ] && echo latest || echo $CI_COMMIT_TAG)-$(sed 's#/#-#g' <<< $CI_SYSTEM_PLATFORM)
  - export CI_COMMIT_TAG=$([ -z $CI_COMMIT_TAG ] && echo latest || echo $CI_COMMIT_TAG)
  - make test
  environment:
    KIND_EXPERIMENTAL_PROVIDER: podman
    CODENAME:
      from_secret: codename
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    CODECOV_TOKEN:
      from_secret: codecov_token
  when:
    event:
    - push
    - tag

depends_on:
- test-e2e